### ISSUE TITLE
Example sketch

### ISSUE THREAD

**Issue by gubagu** [netguy204/OakOLED#1]
Hello,
Just installed the library but i have difficulties using it. Is there a example sketch ?

Thanks in advance, Guby

**Comment by netguy204** [comment]
Thanks @gubagu, I forgot the examples.

I've just made release 0.91. Can you give those examples a shot and let me know how they work for you? Patches welcome if you fix anything or think something deserves more explanation.

https://github.com/netguy204/OakOLED/releases/tag/v0.91

Best, Brian

**Comment by gubagu** [comment]
Thank you Brian !
